# Generated by Django 6.0.2 on 2026-02-04 07:15

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_product_code_alter_product_discounted_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=75, scale=None, size=[500, 300], upload_to='product/'),
        ),
    ]
